language: python
dist: bionic  # OpenSSL 1.1.1
cache:
  directories:
  - $HOME/.cache/pip
  - .tox

jobs:
    include:
        # run custom root tests
        # isotp
        - os: linux
          python: 3.8
          env:
            - TOXENV=#L38-isotp_kernel_module,

install:
  - bash .config/ci/install.
  - python -c "from scapy.all import conf; print(repr(conf))"

script: bash .config/ci/test.
